### ISSUE TITLE
Formatting issues in Lexer and Stemmer JS

### ISSUE THREAD

**Issue by aphundt** [eddiestacks/mentors-suggestions#14]
On uploading the app through native means, jshint throws formatting errors on Lexer and Stemmer JS files:

Upload Error
JSHint errors in ["lib/lexer.js", [{"id"=>"(error)", "raw"=>"Unnecessary semicolon.", "code"=>"W032", "evidence"=>" var noURLorEmail = lcaseInput.replace(re_weburl, \" \").replace(re_email, \" \");;", "line"=>27, "character"=>82, "scope"=>"(main)", "reason"=>"Unnecessary semicolon."}, {"id"=>"(error)", "raw"=>"Use '{a}' to compare with '{b}'.", "code"=>"W041", "evidence"=>" if (stemmedWords.length == 0) {", "line"=>48, "character"=>29, "scope"=>"(main)", "a"=>"===", "b"=>"0", "reason"=>"Use '===' to compare with '0'."}, {"id"=>"(error)", "raw"=>"Missing semicolon.", "code"=>"W033", "evidence"=>" return stemObject.stem == stemmedWord", "line"=>61, "character"=>46, "scope"=>"(main)", "reason"=>"Missing semicolon."}, {"id"=>"(error)", "raw"=>"Missing semicolon.", "code"=>"W033", "evidence"=>" return b.stemmedFrequency - a.stemmedFrequency", "line"=>106, "character"=>53, "scope"=>"(main)", "reason"=>"Missing semicolon."}, {"id"=>"(error)", "raw"=>"Missing semicolon.", "code"=>"W033", "evidence"=>" }", "line"=>138, "character"=>8, "scope"=>"(main)", "reason"=>"Missing semicolon."}, {"id"=>"(error)", "raw"=>"Missing semicolon.", "code"=>"W033", "evidence"=>" }", "line"=>147, "character"=>8, "scope"=>"(main)", "reason"=>"Missing semicolon."}]]: L27: Unnecessary semicolon. L48: Use '===' to compare with '0'. L61: Missing semicolon. L106: Missing semicolon. L138: Missing semicolon. L147: Missing semicolon.

**Comment by epritchard** [comment]
Additional errors from Stemmer.js after resolving issues in Lexer.js

Upload Error
JSHint errors in ["lib/stemmer.js", [{"id"=>"(error)", "raw"=>"'{a}' is already defined.", "code"=>"W004", "evidence"=>" var fp = re2.exec(w);", "line"=>97, "character"=>16, "scope"=>"(main)", "a"=>"fp", "reason"=>"'fp' is already defined."}, {"id"=>"(error)", "raw"=>"'{a}' is already defined.", "code"=>"W004", "evidence"=>" var fp = re.exec(w);", "line"=>119, "character"=>16, "scope"=>"(main)", "a"=>"fp", "reason"=>"'fp' is already defined."}, {"id"=>"(error)", "raw"=>"'{a}' is already defined.", "code"=>"W004", "evidence"=>" var fp = re.exec(w);", "line"=>130, "character"=>16, "scope"=>"(main)", "a"=>"fp", "reason"=>"'fp' is already defined."}, {"id"=>"(error)", "raw"=>"'{a}' is already defined.", "code"=>"W004", "evidence"=>" var fp = re.exec(w);", "line"=>142, "character"=>16, "scope"=>"(main)", "a"=>"fp", "reason"=>"'fp' is already defined."}, {"id"=>"(error)", "raw"=>"'{a}' is already defined.", "code"=>"W004", "evidence"=>" var fp = re.exec(w);", "line"=>155, "character"=>16, "scope"=>"(main)", "a"=>"fp", "reason"=>"'fp' is already defined."}, {"id"=>"(error)", "raw"=>"'{a}' is already defined.", "code"=>"W004", "evidence"=>" var fp = re2.exec(w);", "line"=>162, "character"=>16, "scope"=>"(main)", "a"=>"fp", "reason"=>"'fp' is already defined."}, {"id"=>"(error)", "raw"=>"'{a}' is already defined.", "code"=>"W004", "evidence"=>" var fp = re.exec(w);", "line"=>173, "character"=>16, "scope"=>"(main)", "a"=>"fp", "reason"=>"'fp' is already defined."}, {"id"=>"(error)", "raw"=>"Missing semicolon.", "code"=>"W033", "evidence"=>" }", "line"=>197, "character"=>6, "scope"=>"(main)", "reason"=>"Missing semicolon."}]]: L97: 'fp' is already defined. L119: 'fp' is already defined. L130: 'fp' is already defined. L142: 'fp' is already defined. L155: 'fp' is already defined. L162: 'fp' is already defined. L173: 'fp' is already defined. L197: Missing semicolon.

**Comment by epritchard** [comment]
Fixed these and the translation file issues.
