### ISSUE TITLE
Answer Suggestion App No Longer Displays Article Modals

### ISSUE THREAD

**Issue by aphundt** [eddiestacks/mentors-suggestions#8]

**Comment by ckumar1** [comment]
Related to our switch to help center. I forgot to copy over the method that handles getting the article. I'm pushing up the fix now

**Comment by ckumar1** [comment]
Fixed by the following commit:
https://github.com/epritchard/ticket-suggestion/commit/7c7806049a3bfa9bf58340e71ddd39bb31819b84
